import streamlit as st
from fpdf import FPDF
import matplotlib.pyplot as plt
import tempfile
import os

class CleanReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.set_text_color(26, 60, 52) # Dark Green
        self.cell(0, 10, 'ESG Comparative Analysis Report (2025)', 0, 1, 'C')
        self.ln(5)
        self.line(10, 25, 200, 25)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Generated by AI Agent - Page {self.page_no()}', 0, 0, 'C')

def create_pdf(metrics_data, summary_text=""):
    """
    Creates a polished PDF report using FPDF.
    """
    pdf = CleanReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- 1. Executive Summary ---
    if summary_text:
        pdf.set_font("Arial", 'B', 14)
        pdf.set_text_color(44, 122, 123) # Teal
        pdf.cell(0, 10, "Executive Summary", 0, 1)
        pdf.ln(2)
        
        pdf.set_font("Arial", size=11)
        pdf.set_text_color(0)
        # Clean markdown
        clean_text = summary_text.replace("**", "").replace("###", "")
        clean_text = clean_text.encode('latin-1', 'replace').decode('latin-1') # Handle unicode
        pdf.multi_cell(0, 7, clean_text)
        pdf.ln(10)
    
    # --- 2. Key Metrics Table ---
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(44, 122, 123)
    pdf.cell(0, 10, "Key Metrics Overview", 0, 1)
    
    # Table Header
    headers = ["Company", "Emissions (MT)", "Energy (TWh)", "Renewable %"]
    col_w = [50, 45, 45, 40]
    
    pdf.set_font("Arial", 'B', 10)
    pdf.set_fill_color(230, 240, 240) # Light Teal
    pdf.set_text_color(0)
    
    for i, h in enumerate(headers):
        pdf.cell(col_w[i], 10, h, 1, 0, 'C', True)
    pdf.ln()
    
    # Table Data
    pdf.set_font("Arial", size=10)
    for index, row in enumerate(metrics_data):
        fill = (index % 2 == 1) # Zebra striping
        if fill: pdf.set_fill_color(245, 245, 245)
        
        comp_name = str(row.get('Company', 'Unknown').split('_')[0])
        em = row.get('carbon_emissions')
        en = row.get('energy_usage')
        ren = row.get('renewable_energy_percent')
        
        # Format
        em_fmt = f"{em/1e6:.1f}M" if em else "-"
        en_fmt = f"{en/1e9:.1f}T" if en else "-" # TWh estimate
        ren_fmt = f"{ren:.1f}%" if ren else "-"
        
        pdf.cell(col_w[0], 10, comp_name, 1, 0, 'L', fill)
        pdf.cell(col_w[1], 10, em_fmt, 1, 0, 'C', fill)
        pdf.cell(col_w[2], 10, en_fmt, 1, 0, 'C', fill)
        pdf.cell(col_w[3], 10, ren_fmt, 1, 1, 'C', fill)
        
    pdf.ln(10)

    # --- 3. Visualization ---
    try:
        # Generate chart image
        names = [d.get('Company', 'Unk').split('_')[0] for d in metrics_data]
        vals = [d.get('carbon_emissions', 0) or 0 for d in metrics_data]
        
        if any(vals):
            plt.figure(figsize=(8, 4))
            bars = plt.bar(names, vals, color='#2c7a7b')
            plt.title('Carbon Emissions Comparison', fontsize=12)
            plt.ylabel('Emissions (CO2e)', fontsize=10)
            plt.grid(axis='y', linestyle='--', alpha=0.7)
            
            # Save temp image
            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
                plt.savefig(tmp.name, bbox_inches='tight', dpi=100)
                img_path = tmp.name
            
            pdf.image(img_path, x=20, w=170)
            plt.close()
            os.remove(img_path)
    except Exception as e:
        pdf.cell(0, 10, f"Error generating chart: {e}", 0, 1)

    return pdf.output(dest='S').encode('latin-1') 
